language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - /bin/bash .travis/build.bash

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.bash
    on:
      branch: master
      tags: false

env:
  global:
    # encrypted docker hub credentials
    - secure: "BJ/b2bPMRVawJGb+qRc8CWPsT6PEC5XWPBHW4AWfLuyGvN1gx4g8LLD4jcvLzt9dyIL2MfFaTNXS6rTDjesienjRO2yRZHUPTs4rvoNa/HJjFRrKJZgDBj/u7TPMXjJ1/4rNzCerOjQMNuGDYJgf+pbUYUp6X6rAjTZ3F3YJJXD1ckeGPGAADnf4SKkkkrTaXR+8K9pe8VAjpnzQdhx9NWtLgkLK/5FmHEzjk5hJmyaRMa2E7oFEgWly+prI2ARzB0oYyjv/4iiS+e9dNGZ/tT2L4yLMrXkC8R4PraUK+X4oqpieqovV2K0U6JQ6ChEjS7joW/CMrMwS+/f+dyhubXmDdgXREiIkDl43AmuDpOig/HDkYNf1rePnH0hDcmW5Z8SxJeD1VHqBIdjOwjDSSdTwlBpBj06xIGagL2ps+Hog2yRzpw9rrnMIPlsEYSmI72Lh4fguUigjR8MIhkT1mZBiIxOPlWBC5CWQ9kADsJW+RB1/qkatvxJj6p0LK6f+EG9NzUyFmTW/op3QOlCPgJnirKM0XYI3gSs0N9a3UzbSaUm7bDd7hxa5J2oTH1yMPCPPVEhTAcvg8tY4+54C2dIC5P3O4TwL78VuUFbpbPRKvCihO0phPRp1x8oOed+EocPwmr8KRBDt0p16QZ5CmftFVA1yntf849LB4BnPstY="
