spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

application:
  authentication:
    client-id: cats-n-dogs
    client-secret: my-special-cats-n-dogs-client-secret
    access-token-uri: http://keycloak:8080/auth/realms/cats-n-dogs/protocol/openid-connect/token
    user-info-uri: http://keycloak:8080/auth/realms/cats-n-dogs/protocol/openid-connect/userinfo
    end-session-endpoint: http://keycloak:8080/auth/realms/cats-n-dogs/protocol/openid-connect/logout
    use-secure-cookies: false
