spring:
  autoconfigure:
    exclude: []

application:
  authentication:
    client-id: cats-n-dogs
    client-secret: my-special-cats-n-dogs-client-secret
    access-token-uri: http://localhost:9090/auth/realms/cats-n-dogs/protocol/openid-connect/token
    user-info-uri: http://localhost:9090/auth/realms/cats-n-dogs/protocol/openid-connect/userinfo
    end-session-endpoint: http://localhost:9090/auth/realms/cats-n-dogs/protocol/openid-connect/logout
    use-secure-cookies: false
